SET LOCAL ideavault.allow_history_delete = 'on';
DROP TABLE IF EXISTS idea_conclusions;
DROP TABLE IF EXISTS activity_events;
DROP TABLE IF EXISTS idea_versions;
DROP TABLE IF EXISTS branch_links;
DROP TABLE IF EXISTS branch_inheritance;
DROP TABLE IF EXISTS relationships;
DROP TABLE IF EXISTS checkpoint_items;
DROP TABLE IF EXISTS action_items;
DROP TABLE IF EXISTS open_questions;
DROP TABLE IF EXISTS insights;
DROP TABLE IF EXISTS evidence;
DROP TABLE IF EXISTS assumptions;
DROP TABLE IF EXISTS decisions;
DROP TABLE IF EXISTS knowledge_items;
DROP FUNCTION IF EXISTS iv_guard_knowledge_content();
ALTER TABLE IF EXISTS branches DROP CONSTRAINT IF EXISTS branches_forked_from_fk;
ALTER TABLE IF EXISTS branches DROP CONSTRAINT IF EXISTS branches_head_fk;
DROP TABLE IF EXISTS checkpoints;
ALTER TABLE IF EXISTS agent_runs DROP CONSTRAINT IF EXISTS agent_runs_user_message_fk;
ALTER TABLE IF EXISTS agent_runs DROP CONSTRAINT IF EXISTS agent_runs_assistant_message_fk;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS agent_runs;
ALTER TABLE IF EXISTS ideas DROP CONSTRAINT IF EXISTS ideas_origin_conversation_fk;
DROP TABLE IF EXISTS conversations;
ALTER TABLE IF EXISTS ideas DROP CONSTRAINT IF EXISTS ideas_default_branch_fk;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS ideas;
DROP TABLE IF EXISTS sources;
